force-app/main/default/objects/Case/fields/Case_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Profile Update</fullName>
            </value>
            <value>
                <fullName>Invoice Related</fullName>
            </value>
            <value>
                <fullName>Payment Related</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Sub_Category__c</fullName>
    <label>Case Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vendor Code</fullName>
            </value>
            <value>
                <fullName>Account Related</fullName>
            </value>
            <value>
                <fullName>Document Related</fullName>
            </value>
            <value>
                <fullName>Email Change</fullName>
            </value>
            <value>
                <fullName>Mobile Change</fullName>
            </value>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>RERA Related</fullName>
            </value>
            <value>
                <fullName>GST Related</fullName>
            </value>
            <value>
                <fullName>BANK Ac. Related</fullName>
            </value>
            <value>
                <fullName>Invoice Preview Query</fullName>
            </value>
            <value>
                <fullName>Amount Discrepancy</fullName>
            </value>
            <value>
                <fullName>Invoice Date Mismatch</fullName>
            </value>
            <value>
                <fullName>Booking Date Mismatch</fullName>
            </value>
            <value>
                <fullName>Base Brokerage Query</fullName>
            </value>
            <value>
                <fullName>Ladder Brokerage Query</fullName>
            </value>
            <value>
                <fullName>Kicker Incentive Query</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Advice</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Lockated_CPCaseDetails.cls
@RestResource(urlMapping='/cpCaseDetails/*')
global without sharing class Lockated_CPCaseDetails {
	
    @HttpGet
    global static List<CaseResponse> checkCaseDetails(){
        
        RestRequest req = RestContext.request;
        String brokerId = req.params.get('brokerId');

        List<CaseResponse> responseList = new List<CaseResponse>();

        if (!String.isBlank(brokerId)) {
            List<Case> brokerCases = [
                SELECT CaseNumber, Subject, Status, Opportunity__r.Name,Case_Category__c,Case_Sub_Category__c,CreatedDate
                FROM Case
                WHERE Opportunity__r.RW_Broker__c = :brokerId
            ];

            for (Case c : brokerCases) {
                CaseResponse res = new CaseResponse();
                res.caseNumber = c.CaseNumber;
                res.subject = c.Subject;
                res.status = c.Status;
                res.opportunityName = c.Opportunity__r.Name;
                res.caseCategory = c.Case_Category__c;           
                res.caseSubCategory = c.Case_Sub_Category__c;   
                res.createdDate = c.CreatedDate;    
                responseList.add(res);
            }
        }

        return responseList; 
		
        
    }
    global class CaseResponse {
        public String caseNumber;
        public String subject;
        public String status;
        public String opportunityName;
        public String caseCategory;      
        public String caseSubCategory;  
        public DateTime createdDate;     
    }
}