force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bank_Names</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker__c/fields/Broker_Type__c.field-meta.xml
<CustomField>
    <fullName>Broker_Type__c</fullName>
    <label>Channel Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Institutional</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Outstation</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>NRI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker__c/fields/Developers_Worked_For__c.field-meta.xml
<CustomField>
    <fullName>Developers_Worked_For__c</fullName>
    <label>Developers Worked For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aadi Properties</fullName>
            </value>
            <value>
                <fullName>Acme</fullName>
            </value>
            <value>
                <fullName>Adani Realty</fullName>
            </value>
            <value>
                <fullName>Adhiraj construction</fullName>
            </value>
            <value>
                <fullName>Ajmera</fullName>
            </value>
            <value>
                <fullName>Akshar group</fullName>
            </value>
            <value>
                <fullName>Arkade Group</fullName>
            </value>
            <value>
                <fullName>Chandak</fullName>
            </value>
            <value>
                <fullName>Damji Shamji Shah</fullName>
            </value>
            <value>
                <fullName>Dosti Group</fullName>
            </value>
            <value>
                <fullName>Ekta world</fullName>
            </value>
            <value>
                <fullName>Godrej Properties</fullName>
            </value>
            <value>
                <fullName>Hiranandani Developers</fullName>
            </value>
            <value>
                <fullName>Hubtown</fullName>
            </value>
            <value>
                <fullName>JP Infra</fullName>
            </value>
            <value>
                <fullName>Kabra developer</fullName>
            </value>
            <value>
                <fullName>Kalpataru</fullName>
            </value>
            <value>
                <fullName>Kanakia</fullName>
            </value>
            <value>
                <fullName>Koltepatil developer</fullName>
            </value>
            <value>
                <fullName>K Raheja Corp</fullName>
            </value>
            <value>
                <fullName>L&amp;T Realty</fullName>
            </value>
            <value>
                <fullName>Lodha Group</fullName>
            </value>
            <value>
                <fullName>Mahindra Lifespaces</fullName>
            </value>
            <value>
                <fullName>Marathon Realty</fullName>
            </value>
            <value>
                <fullName>Oberoi Realty</fullName>
            </value>
            <value>
                <fullName>Ornate Universal</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paradise group</fullName>
            </value>
            <value>
                <fullName>Piramal Realty</fullName>
            </value>
            <value>
                <fullName>Puranik Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-1 yrs</fullName>
            </value>
            <value>
                <fullName>1-5 yrs</fullName>
            </value>
            <value>
                <fullName>5-10 yrs</fullName>
            </value>
            <value>
                <fullName>10-15 yrs</fullName>
            </value>
            <value>
                <fullName>15-20 yrs</fullName>
            </value>
            <value>
                <fullName>20+ yrs</fullName>
            </value>
            <value>
                <fullName>0-1, 1-5, 5-10, 10-15, 15-20, 20+</fullName>
                <isActive>false</isActive>
                <label>0-1, 1-5, 5-10, 10-15, 15-20, 20+</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Rentals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker__c/fields/Place_of_Supply__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Supply__c</fullName>
    <label>Place of Supply</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>CHANDIGARH</fullName>
            </value>
            <value>
                <fullName>UTTARAKHAND</fullName>
            </value>
            <value>
                <fullName>HARYANA</fullName>
            </value>
            <value>
                <fullName>DELHI</fullName>
            </value>
            <value>
                <fullName>RAJASTHAN</fullName>
            </value>
            <value>
                <fullName>UTTAR PRADESH</fullName>
            </value>
            <value>
                <fullName>BIHAR</fullName>
            </value>
            <value>
                <fullName>SIKKIM</fullName>
            </value>
            <value>
                <fullName>ARUNACHAL PRADESH</fullName>
            </value>
            <value>
                <fullName>NAGALAND</fullName>
            </value>
            <value>
                <fullName>MANIPUR</fullName>
            </value>
            <value>
                <fullName>MIZORAM</fullName>
            </value>
            <value>
                <fullName>TRIPURA</fullName>
            </value>
            <value>
                <fullName>MEGHALAYA</fullName>
            </value>
            <value>
                <fullName>ASSAM</fullName>
            </value>
            <value>
                <fullName>WEST BENGAL</fullName>
            </value>
            <value>
                <fullName>JHARKHAND</fullName>
            </value>
            <value>
                <fullName>ODISHA</fullName>
            </value>
            <value>
                <fullName>CHATTISGARH</fullName>
            </value>
            <value>
                <fullName>MADHYA PRADESH</fullName>
            </value>
            <value>
                <fullName>GUJARAT</fullName>
            </value>
            <value>
                <fullName>DADRA AND NAGAR HAVELI AND DAMAN AND DIU (NEWLY MERGED UT)</fullName>
            </value>
            <value>
                <fullName>ANDHRA PRADESH(BEFORE DIVISION)</fullName>
            </value>
            <value>
                <fullName>KARNATAKA</fullName>
            </value>
            <value>
                <fullName>GOA</fullName>
            </value>
            <value>
                <fullName>LAKSHADWEEP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Runwal Bliss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Place_of_Supply__c/Place_of_Supply__c.object-meta.xml
<CustomObject>
    <label>Place of Supply</label>
    <nameField>
        <label>Place of Supply Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Place of Supply</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Place_of_Supply__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Supply__c</fullName>
    <label>Place of Supply</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/RW_Status__c.field-meta.xml
<CustomField>
    <fullName>RW_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Bank_Names.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aadhar Housing Finance ltd</fullName>
    </customValue>
    <customValue>
        <fullName>Abhyudaya Co-operative Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Aditya Birla Housing Finance Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>Ahmedabad Mercantile Co-Op Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Akola Janata Commercial Co-operative Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Akola Urban Co-operative Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Allahabad Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Andaman and Nicobar State Co-operative Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh Mahesh Co-Op Urban Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh State Co-operative Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Apna Sahakari Bank Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh State Co-operative Apex Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Assam Co-operative Apex Bank</fullName>
    </customValue>
    <customValue>
        <fullName>AU SMALL FINANCE BANK</fullName>
    </customValue>
    <customValue>
        <fullName>Axis Bank Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>Bajaj Housing Finance Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>Bank of Baroda</fullName>
    </customValue>
    <customValue>
        <fullName>Bank of India</fullName>
    </customValue>
    <customValue>
        <fullName>Bank of Maharashtra</fullName>
    </customValue>
    <customValue>
        <fullName>Bassein Catholic Co-operative Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Bharat Co-operative Bank Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>Bharati Sahakari Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Bharat Petroleum Corporation Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar State Co-operative Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Bombay Mercantile Co-operative Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Canara Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Capri Global Housing Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Catholic Syrian Bank Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>Central Bank of India</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh State Co-operative Bank</fullName>
    </customValue>
    <masterLabel>Bank Names</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Lockated_CPGetPicklistValues.cls
@RestResource(urlMapping='/cpGetPicklistValues/*')
global without sharing class Lockated_CPGetPicklistValues {
    
    @HttpGet
    global static ResponseWrapper doGet() {
        ResponseWrapper res = new ResponseWrapper();

        //Get Projects
        /*if (data == 'getProjects') {
            for (Project__c proj : [SELECT Name FROM Project__c WHERE RW_Status__c = 'Active']) {
                res.values.add(proj.Name);
            }
        }*/
        //Get CP Type
        res.getCPType = getPicklistValues('Broker__c', 'Broker_Type__c');
        //Get Experience Values
        res.getCPExperiences = getPicklistValues('Broker__c', 'Experience__c');
        //Get Operation Place Values
        res.getCPOperationPlaces = getPicklistValues('Broker__c', 'Place_of_Supply__c');
        //Get Expertise Values
        res.getCPExpertise = getPicklistValues('Broker__c', 'Expertise__c');
        //Get Developers Worked For Values
        res.getDevelopersWorkedFor = getPicklistValues('Broker__c', 'Developers_Worked_For__c');
        //Get Bank Names
        res.getBankNames = getPicklistValues('Broker__c', 'Bank_Name__c');
        
        return res;
    }
    
    global class ResponseWrapper {
        //public String getProjects;
        public list<String> getCPType;
        public list<String> getCPExperiences;
        public list<String> getCPOperationPlaces;
        public list<String> getCPExpertise;
		public list<String> getDevelopersWorkedFor;
        public list<String> getBankNames;
    }
    
    private static List<String> getPicklistValues(String objectName, String fieldName) {
        Schema.DescribeFieldResult fieldDescribe =
            Schema.getGlobalDescribe().get(objectName)
                  .getDescribe()
                  .fields.getMap().get(fieldName)
                  .getDescribe();
        
        List<String> results = new List<String>();
        for (Schema.PicklistEntry entry : fieldDescribe.getPicklistValues()) {
            results.add(entry.getLabel());
        }
        return results;
    }
}