force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker__c/fields/RW_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>RW_Mobile_No__c</fullName>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Broker__c/recordTypes/Channel_Partner.recordType-meta.xml
<RecordType>
    <fullName>Channel_Partner</fullName>
    <active>true</active>
    <label>Channel Partner</label>
</RecordType>

force-app/main/default/objects/Broker__c/recordTypes/Temp_Channel_Partner.recordType-meta.xml
<RecordType>
    <fullName>Temp_Channel_Partner</fullName>
    <active>true</active>
    <description>Temporary CPs</description>
    <label>Temp Channel Partner</label>
</RecordType>

force-app/main/default/objects/Lead/fields/RW_Broker__c.field-meta.xml
<CustomField>
    <fullName>RW_Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.LeadSource</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.LeadSource</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RW_Project__c.field-meta.xml
<CustomField>
    <fullName>RW_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please Select an Active Project</errorMessage>
        <filterItems>
            <field>Project__c.RW_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Lockated_CPAddLead.cls
@RestResource(urlMapping='/cpAddLead/*')
global without sharing class Lockated_CPAddLead {

    // Input Wrapper
    global class LeadInput {
        public String customerName;
        public String mobileNumber;
        public String email;
        public String propertyType;
        public String projectInterested;
        public String cpId;
    }

    // Response Wrapper
    global class LeadResponse {
        public String status;
        public String message;
        public String leadId;
    }

    @HttpPost
    global static void doPost() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');

        LeadResponse response = new LeadResponse();

        try {
            // Deserialize the incoming JSON body
            LeadInput input = (LeadInput)JSON.deserialize(req.requestBody.toString(), LeadInput.class);

            // Validate mandatory fields
            if(String.isBlank(input.customerName) || String.isBlank(input.mobileNumber)) {
                response.status = 'error';
                response.message = 'Customer Name and Mobile Number are required';
                res.statusCode = 400;
                res.responseBody = Blob.valueOf(JSON.serialize(response));
                return;
            }
            List<Broker__c> brlist = [Select Id,RecordTypeId,RecordType.DeveloperName from Broker__c where Id =: input.cpId];
            // Create Lead
            Lead newLead = new Lead();
            newLead.LastName = input.customerName;
            newLead.RW_Mobile_No__c = input.mobileNumber;
            newLead.Email = input.email;
            newLead.RW_Project__c = input.projectInterested;
            newLead.RW_Broker__c = input.cpId;
            if(!brlist.isEmpty() && brlist.size()>0){
                newLead.RW_Broker__c = brlist[0].Id;
                if(brlist[0].RecordType.DeveloperName =='Channel_Partner'){
                 newLead.LeadSource = 'Channel partner';
                }
                if(brlist[0].RecordType.DeveloperName =='Temp_Channel_Partner'){
                 newLead.LeadSource = 'Temp Channel Partner';
                }
                
            }
            

            insert newLead;

            response.status = 'success';
            response.message = 'Lead added successfully';
            response.leadId = newLead.Id;
            res.statusCode = 200; // Created
            res.responseBody = Blob.valueOf(JSON.serialize(response));

        } catch(Exception e) {
            response.status = 'error';
            response.message = e.getMessage();
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(JSON.serialize(response));
        }
    }
}