force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker__c/fields/AOP_Type__c.field-meta.xml
<CustomField>
    <fullName>AOP_Type__c</fullName>
    <description>For AOP Categorization</description>
    <inlineHelpText>For AOP Categorization</inlineHelpText>
    <label>CP Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AOP</fullName>
            </value>
            <value>
                <fullName>Non AOP</fullName>
            </value>
            <value>
                <fullName>ICP</fullName>
            </value>
            <value>
                <fullName>RCP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Runwal Bliss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner New</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Channel_Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Category__c/CP_Category__c.object-meta.xml
<CustomObject>
    <description>This object maintains the CP Category based on CP as well as project wise</description>
    <label>CP Category</label>
    <nameField>
        <displayFormat>CPC-{000000}</displayFormat>
        <label>CP Category</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>P4</fullName>
                <default>true</default>
                <label>P4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Category__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>CP Category</relationshipLabel>
    <relationshipName>CP_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Category__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Category</relationshipLabel>
    <relationshipName>CP_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CP_Category__c.field-meta.xml
<CustomField>
    <fullName>CP_Category__c</fullName>
    <description>For CP Categorization</description>
    <inlineHelpText>For CP Categorization</inlineHelpText>
    <label>CP Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>P4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_reference_Booked_Unit__c.field-meta.xml
<CustomField>
    <fullName>Customer_reference_Booked_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer reference Booked Unit</label>
    <referenceTo>Project_Unit__c</referenceTo>
    <relationshipLabel>Opportunities (Customer reference Booked Unit)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Reference_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reference_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Reference Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Customer Reference Opportunity)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_reference_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_reference_SAP_Code__c</fullName>
    <label>Customer reference SAP Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Booking_Date_Opp__c.field-meta.xml
<CustomField>
    <fullName>RW_Booking_Date_Opp__c</fullName>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Project__c.field-meta.xml
<CustomField>
    <fullName>RW_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Project_Unit__c.field-meta.xml
<CustomField>
    <fullName>RW_Project_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Unit</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Doesn&apos;t match filter criteria.</errorMessage>
        <filterItems>
            <field>Project_Unit__c.RW_Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.RW_Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Project_Unit__c.RW_Seventh_Day__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Walkin_Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>RW_Walkin_Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Walkin Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Walkin_Source__c</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.Walkin_Source__c</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Opportunities (Walkin Channel Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Walkin_Customer_Reference__c.field-meta.xml
<CustomField>
    <fullName>RW_Walkin_Customer_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Walkin Customer Reference</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Walkin Customer Reference)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Number__c</fullName>
    <label>SAP Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Unit__c/Project_Unit__c.object-meta.xml
<CustomObject>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Unit__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Channel Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Unit__c/fields/RW_Customer__c.field-meta.xml
<CustomField>
    <fullName>RW_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Units</relationshipLabel>
    <relationshipName>Project_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Unit__c/fields/RW_Project__c.field-meta.xml
<CustomField>
    <fullName>RW_Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Units</relationshipLabel>
    <relationshipName>Project_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/trgOppHandler.cls
public class trgOppHandler {

    public static void addAopTypeAndCpCategory(List<Opportunity> cpOppList){
        
        Set<String> projects = new Set<String>();
        Set<String> cps = new Set<String>();
        for(Opportunity opp : cpOppList){
            projects.add(opp.RW_Project__c);
            cps.add(opp.RW_Walkin_Channel_Partner__c);
        }
        
        //List<CP_Category__c> cpCategoryList = [SELECT Id,Name,Category__c,Channel_Partner__c,Project__c FROM CP_Category__c WHERE Project__c =: projects AND Channel_Partner__c =: cps AND Category__c != null];
        Map<String,String> categoryMap = new Map<String, String>();
        Map<Id, Broker__c> brokers;
        if(cps.size() > 0){
            for(CP_Category__c cat : [SELECT Id,Name,Category__c,Channel_Partner__c,Project__c FROM CP_Category__c WHERE Project__c =: projects AND Channel_Partner__c =: cps AND Category__c != null]){
                categoryMap.put(cat.Project__c + '_' + cat.Channel_Partner__c, cat.Category__c);
            }
            brokers = new Map<Id, Broker__c>([SELECT Id,AOP_Type__c FROM Broker__c WHERE Id =: cps]);
        }
        
               
        for(Opportunity opp : cpOppList){
            if(!categoryMap.isEmpty()){
                opp.CP_Category__c = categoryMap.get(opp.RW_Project__c + '_' + opp.RW_Walkin_Channel_Partner__c);
            }
            if(!brokers.isEmpty() && brokers.get(opp.RW_Walkin_Channel_Partner__c) != null){
                opp.AOP_Type__c = brokers.get(opp.RW_Walkin_Channel_Partner__c).AOP_Type__c;
            }
        }
    }
    
    public static void updateReferralCustDetails(List<Opportunity> refOppList){
        /*
        Set<String> custRefs = new Set<String>();
        for(Opportunity opp : refOppList){
            custRefs.add(opp.RW_Walkin_Customer_Reference__c);
        }
        */
        //List<Opportunity> lstOpp = [Select Id,StageName,RW_Booking_Date_Opp__c, Name,SAP_Customer_Number__c,AccountId,RW_Project_Unit__c /*Customer_Reference_Opportunity__c*/ From Opportunity Where AccountId=: custRefs AND StageName =:'Unit Booked'  ORDER BY RW_Booking_Date_Opp__c DESC ];
        /*Map<String, Opportunity> refOppMap = new Map<String, Opportunity>();
        if(custRefs.size() > 0){
            for(Opportunity opp : [Select Id,StageName,RW_Booking_Date_Opp__c, Name,SAP_Customer_Number__c,AccountId,RW_Project_Unit__c,Customer_Reference_Opportunity__c From Opportunity Where AccountId=: custRefs AND StageName =:'Unit Booked'  ORDER BY RW_Booking_Date_Opp__c DESC ]){
                refOppMap.put(opp.AccountId, opp);
            }
        }
        
        for(Opportunity opp : refOppList){
            if(refOppMap.get(opp.RW_Walkin_Customer_Reference__c) != null){
                opp.Customer_reference_SAP_Code__c = refOppMap.get(opp.RW_Walkin_Customer_Reference__c).SAP_Customer_Number__c;
                opp.Customer_reference_Booked_Unit__c = refOppMap.get(opp.RW_Walkin_Customer_Reference__c).RW_Project_Unit__c;
                opp.Customer_Reference_Opportunity__c = refOppMap.get(opp.RW_Walkin_Customer_Reference__c).Id;
            }
        }*/
        
    }
    
  /*  public static void updateCustRefOpp(Map<Id,Id> oppIdVsrefBookedUnitIds){
        system.debug('Inside updateCustRefOpp');
        Map<Id,Id> custRefUnitIdsVsOppIds = new Map<Id,Id>();
        list<Opportunity> opplist = new list<Opportunity>();
        list<Project_Unit__c> pulist = [Select Id,RW_Customer__c from Project_Unit__c where Id in: oppIdVsrefBookedUnitIds.values()];
        if(!pulist.isEmpty()){
            For(Project_Unit__c pu: pulist){
                custRefUnitIdsVsOppIds.put(pu.Id,pu.RW_Customer__c);
            }
        }
        if(!custRefUnitIdsVsOppIds.isEmpty()){
            system.debug('Inside custRefUnitIdsVsOppIds');
            For(Id oppId : oppIdVsrefBookedUnitIds.keySet()){
                Opportunity opp = new Opportunity();
                opp.Id = oppId;
                opp.Customer_Reference_Opportunity__c = custRefUnitIdsVsOppIds.get(oppIdVsrefBookedUnitIds.get(oppId));
            }
        }
    }*/
    
    // Added by Prashant 01-08-2025 START
    public static void updateCustRefOpp(Map<Id, Id> oppIdVsrefBookedUnitIds,Map<Id, Opportunity> newMap) {
        system.debug('Inside updateCustRefOpp');
        Map<Id, Id> custRefUnitIdsVsOppIds = new Map<Id, Id>();
        List<Project_Unit__c> pulist = [SELECT Id, RW_Customer__c  FROM Project_Unit__c WHERE Id IN :oppIdVsrefBookedUnitIds.values()];
        
        for (Project_Unit__c pu : pulist) {
            custRefUnitIdsVsOppIds.put(pu.Id, pu.RW_Customer__c);
        }
        
        for (Id oppId : oppIdVsrefBookedUnitIds.keySet()) {            
            if (custRefUnitIdsVsOppIds.get(oppIdVsrefBookedUnitIds.get(oppId)) != null && newMap.containsKey(oppId)) {
                newMap.get(oppId).Customer_Reference_Opportunity__c = custRefUnitIdsVsOppIds.get(oppIdVsrefBookedUnitIds.get(oppId));
            }
        }
    }
    // Added by Prashant 01-08-2025 END

}