force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <label>Brokerage %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Brokerage_Summary__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brokerage Summary</label>
    <referenceTo>Brokerage_Summary__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Runwal Bliss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brokerage__c/Brokerage__c.object-meta.xml
<CustomObject>
    <label>Brokerage</label>
    <nameField>
        <label>Brokerage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokerages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brokerage__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Brokerages</relationshipLabel>
    <relationshipName>Brokerages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brokerages</relationshipLabel>
    <relationshipName>Brokerages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <label>Brokerage%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Brokerage_Summary__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Summary__c</fullName>
    <label>Brokerage Summary</label>
    <referenceTo>Brokerage_Summary__c</referenceTo>
    <relationshipLabel>Brokerages</relationshipLabel>
    <relationshipName>Brokerages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Brokerages</relationshipLabel>
    <relationshipName>Brokerages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/Brokerage_Invoice__c.object-meta.xml
<CustomObject>
    <label>Brokerage Invoice Line Item</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>Brokerage Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <label>Brokerage %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Brokerage_Summary__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brokerage Summary</label>
    <referenceTo>Brokerage_Summary__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Brokerage_Summary__r.Project__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brokerage_Summary__c/Brokerage_Summary__c.object-meta.xml
<CustomObject>
    <label>Brokerage Summary</label>
    <nameField>
        <displayFormat>BS-{000000000}</displayFormat>
        <label>Brokerage No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brokerage_Summary__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Brokerage Summary</relationshipLabel>
    <relationshipName>Brokerage_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Summary__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brokerage Summary</relationshipLabel>
    <relationshipName>Brokerage_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Summary__c/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <formula>Total_Brokerage__c  /  Booking__r.Agreement_Value_for_brokers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Brokerage %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Brokerage_Summary__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Brokerage Summary</relationshipLabel>
    <relationshipName>Brokerage_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Summary__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;Brokerage_Summary&apos;  , Booking__r.RW_Project_Name__c, Project_Lookup__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner New</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Channel_Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Brokerage__c/CP_Brokerage__c.object-meta.xml
<CustomObject>
    <label>CP Brokerage Invoices</label>
    <nameField>
        <displayFormat>CPB-{0000}</displayFormat>
        <label>CP Brokerage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Brokerage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Brokerage__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Broker__c</referenceTo>
    <relationshipName>CP_Brokerage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Brokerage__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipName>CP_Brokerage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <label>Brokerage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProjectName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MonthwiseBrokerageRecordsTest.cls
@isTest
public class MonthwiseBrokerageRecordsTest {

    @testSetup
    static void setupTestData() {
        Project__c P1 = new Project__c( Name='Project1');
        insert P1;
        
        // Create Legal Entity (on Tower)
        Legal_Entity__c legalEntity = new Legal_Entity__c(Name = 'Test Legal Entity');
                      
        insert legalEntity;

        // Create Tower with Legal Entity
        Tower__c tower = new Tower__c(
            Name = 'Test Tower',
            ProjectName__c =P1.Id,
            Legal_Entity__c = legalEntity.Id
        );
        insert tower;

        // Create Channel Partner
        Broker__c channelPartner = new Broker__c(Name = 'Test broker');
        insert channelPartner;

        // Create Booking
        Booking__c booking = new Booking__c(
         //   Name = 'Test Booking',
            Tower__c = tower.Id
        );
        insert booking;
        
        Brokerage_Summary__c summary = new Brokerage_Summary__c(
        
    );
    insert summary;

        
        Brokerage__c brokerage = new Brokerage__c(
        Name = 'Additional Brokerage',
            Brokerage_Summary__c=summary.id
          
    );
    insert brokerage;

        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];

        User u1 = new User(
            Alias = 'testu',
            Email = 'testuser@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            UserName = 'unique_testuser' + DateTime.now().getTime() + '@example.com'
        );
        insert u1;


        // Create invoices for THIS_MONTH
        List<Brokerage_Invoice__c> invoices = new List<Brokerage_Invoice__c>();
        for (Integer i = 0; i < 3; i++) {
            invoices.add(new Brokerage_Invoice__c(
                Booking__c = booking.Id,
                Channel_Partner__c = channelPartner.Id,
                Invoice_Amount__c = 1000 + i,
                Brokerage_In_Rs__c =989 +1,
                Brokerage__c =0.5,
                CP_Invoice_Clearing_L1__c= u1.id,
                CP_Invoice_Clearing_L2__c =u1.id,
                Total_Agreement_Value__c= 123456 +i,
                Brokerage_Lookup__c = brokerage.Id
            ));
        }
        insert invoices;
    }

   
     @isTest
    static void testMonthwiseBrokerageBatch() {
        Test.startTest();
        // Use a larger scope to ensure only one execute runs
        MonthwiseBrokerageRecords batch = new MonthwiseBrokerageRecords();
        Database.executeBatch(batch, 200);
        Test.stopTest();

        // Verify CP_Brokerage__c created
     
   
}
}