force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/BrokerIId__c.field-meta.xml
<CustomField>
    <fullName>BrokerIId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Source_of_Booking__c</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.Source_of_Booking__c</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Booking20</relationshipLabel>
    <relationshipName>Booking20</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Locality__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Central Zone 1</fullName>
            </value>
            <value>
                <fullName>Central Zone 2</fullName>
            </value>
            <value>
                <fullName>Central Zone 3</fullName>
            </value>
            <value>
                <fullName>Kalyan Dombivali</fullName>
            </value>
            <value>
                <fullName>Navi Mumbai</fullName>
            </value>
            <value>
                <fullName>NRI</fullName>
            </value>
            <value>
                <fullName>Outstation</fullName>
            </value>
            <value>
                <fullName>South Bombay</fullName>
            </value>
            <value>
                <fullName>Thane and beyond</fullName>
            </value>
            <value>
                <fullName>Western Zone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Budget_In_Cr__c.field-meta.xml
<CustomField>
    <fullName>Budget_In_Cr__c</fullName>
    <label>Budget(In Cr)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Walkin_Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>RW_Walkin_Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Walkin Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Walkin_Source__c</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.Walkin_Source__c</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Opportunities (Walkin Channel Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <formula>Text(Account.Zone__c)</formula>
    <label>Zone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Lockated_CPCustomerAnalytics.cls
@RestResource(urlMapping='/cpCustomerAnalytics/*')
global without sharing class Lockated_CPCustomerAnalytics {
    @HttpGet
    global static void doGet()
    {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        String cpId = req.params.get('cpId');
        Map<String, Object> errorResult = new Map<String, Object>();
        if(String.isBlank(cpId)){
            errorResult.put('status', 'error');
            errorResult.put('message', 'Please pass valid CP Id');
            res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
            res.statusCode = 400;
        }else{
            try{
                ResponseWrapper resp = new ResponseWrapper();
                list<Broker__c> brs = [Select Id,RecordTypeId from Broker__c where Id =: cpId limit 1];  
                Id CPRecordTypeId = Schema.SObjectType.Broker__c.getRecordTypeInfosByName().get('Channel Partner').getRecordTypeId();
                Id TempCPRecordTypeId = Schema.SObjectType.Broker__c.getRecordTypeInfosByName().get('Temp Channel Partner').getRecordTypeId();
                if(!brs.isEmpty()){
                    list<Opportunity> olist = [Select id,Budget_In_Cr__c,Zone__c from Opportunity  where RW_Walkin_Channel_Partner__c =: cpId and Budget_In_Cr__c != null ];
                    if(!olist.isEmpty()){
                        Decimal avgClientBudget = 0;
                        for(Opportunity o:olist){
                            if(brs[0].RecordTypeId == CPRecordTypeId){
                                resp.totalWalkIns += 1;
                                avgClientBudget += o.Budget_In_Cr__c;
                            }else if(brs[0].RecordTypeId == TempCPRecordTypeId){
                                resp.totalWalkIns += 1;
                                avgClientBudget += o.Budget_In_Cr__c;
                            }
                        }
                        resp.avgClientBudget = (avgClientBudget / resp.totalWalkIns).setScale(0, RoundingMode.HALF_UP);

                    }else{
                        errorResult.put('status', 'error');
                        errorResult.put('message', 'No Customer Records Found');
                        res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                        res.statusCode = 400;
                    }
                    list<Booking__c> blist = [Select id from Booking__c where BrokerIId__c =: cpId ];
                    if(!blist.isEmpty()){
                        for(Booking__c b : blist){
                            if(brs[0].RecordTypeId == CPRecordTypeId){
                                resp.totalBookings += 1;
                            }else if(brs[0].RecordTypeId == TempCPRecordTypeId){
                                resp.totalBookings += 1;
                            }
                        }
                    }else{
                        errorResult.put('status', 'error');
                        errorResult.put('message', 'No Booking Records Found');
                        res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                        res.statusCode = 400;
                    }                    
                    res.responseBody = Blob.valueOf(JSON.serialize(resp));
                    res.statusCode = 200;
                }else{
                    errorResult.put('status', 'error');
                    errorResult.put('message', 'No CP Record Found');
                    res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                    res.statusCode = 400;
                }            
            }catch(exception e){
                errorResult.put('status', 'error');
                errorResult.put('message', e.getMessage() + ';  ' + e.getStackTraceString());
                res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                res.statusCode = 400;
            }
        }
    }   
    
    global class ResponseWrapper {
        public Integer totalWalkIns = 0;
        public Integer totalBookings = 0;
        public Decimal avgClientBudget = 0;
        public String activeZones;//??
    } 
}