force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Additional_Brokerage_Accrued_Dashboards__c.field-meta.xml
<CustomField>
    <fullName>Additional_Brokerage_Accrued_Dashboards__c</fullName>
    <label>Additional Brokerage Accrued(Dashboards)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Agreement_Value_for_brokers__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_for_brokers__c</fullName>
    <formula>IF(ISPICKVAL(Source_of_Booking__c, &apos;Channel Partner&apos;),IF(AND(Old_Booking__c != null,ISPICKVAL(Unit_Trasfer_to_Project__c , &apos;Same Project&apos;),NOT(ISPICKVAL(Unit_Trasfer_to_Project__c , &apos;Different Project&apos;)),NOT(ISPICKVAL(Unit_Trasfer_to_Project__c , &apos;&apos;))   ), IF(Old_Booking__r.Agreement_Value_for_broker_calculation__c &lt; Agreement_Value_for_broker_calculation__c , Old_Booking__r.Agreement_Value_for_broker_calculation__c, Agreement_Value_for_broker_calculation__c)  ,
			Agreement_Value_for_broker_calculation__c),0)</formula>
    <label>Agreement Value for brokers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Base_Brokerage_Accrued_Dashboards__c.field-meta.xml
<CustomField>
    <fullName>Base_Brokerage_Accrued_Dashboards__c</fullName>
    <label>Base Brokerage Accrued (Dashboards)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Brokerage_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brokerage Scheme</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Please ensure the approved brokerage scheme is tagged appropriately</errorMessage>
        <filterItems>
            <field>Brokerage_Scheme__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved by Level 2</value>
        </filterItems>
        <filterItems>
            <field>$User.Username</field>
            <operation>equals</operation>
            <value>stetig.admin@runwal.com</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Brokerage_Scheme__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/BrokerIId__c.field-meta.xml
<CustomField>
    <fullName>BrokerIId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Source_of_Booking__c</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.Source_of_Booking__c</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Booking20</relationshipLabel>
    <relationshipName>Booking20</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Source_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Booking__c</fullName>
    <label>Source of Booking</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Employee / Managemen</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>R Circle Caller</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Temp Channel Partner</fullName>
            </value>
            <value>
                <fullName>PreSales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Unit Booked</fullName>
            </value>
            <value>
                <fullName>Booking Received</fullName>
            </value>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>Booking Blocked</fullName>
            </value>
            <value>
                <fullName>Booking Registered</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Sent for Revision</fullName>
            </value>
            <value>
                <fullName>Cancellation Initiated</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Pending</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Ready</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled - Refunded</fullName>
            </value>
            <value>
                <fullName>Booking Received - Payment Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brokerage_Scheme__c/Brokerage_Scheme__c.object-meta.xml
<CustomObject>
    <label>Brokerage Scheme</label>
    <nameField>
        <label>Brokerage Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokerage Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brokerage_Scheme__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Sent for Approval</fullName>
                <default>true</default>
                <label>Not Sent for Approval</label>
            </value>
            <value>
                <fullName>Pending Level 1 Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Level 1</fullName>
            </value>
            <value>
                <fullName>Pending Level 2 Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Level 2</fullName>
            </value>
            <value>
                <fullName>Rejected by Level 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brokerage_Scheme__c/fields/Slab_Type__c.field-meta.xml
<CustomField>
    <fullName>Slab_Type__c</fullName>
    <label>Slab Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Count</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brokerage_Scheme__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>NRI</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brokerage_Slab__c/Brokerage_Slab__c.object-meta.xml
<CustomObject>
    <label>Brokerage Slab</label>
    <nameField>
        <label>Brokerage Slab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokerage Slabs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brokerage_Slab__c/fields/Brokerage_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brokerage Scheme</label>
    <referenceTo>Brokerage_Scheme__c</referenceTo>
    <relationshipLabel>Brokerage Slabs</relationshipLabel>
    <relationshipName>Brokerage_Slabs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Slab__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brokerage_Slab__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brokerage_Slab__c/fields/Total_Brokerage_for_Local_Bookings__c.field-meta.xml
<CustomField>
    <fullName>Total_Brokerage_for_Local_Bookings__c</fullName>
    <formula>Brokerage_Scheme__r.Base_Brokerage_for_Local_Bookings__c + Additional_Brokerage_for_Local_Bookings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Brokerage for Local Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Brokerage_Slab__c/fields/Total_Brokerage_for_OS_NRI__c.field-meta.xml
<CustomField>
    <fullName>Total_Brokerage_for_OS_NRI__c</fullName>
    <formula>Brokerage_Scheme__r.Base_Brokerage_for_OS_NRI__c + Additional_Brokerage_for_OS_NRI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Brokerage for OS / NRI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Lockated_CPGetLadderProgress.cls
@RestResource(urlMapping='/cpGetLadderProgress/*')
global without sharing class Lockated_CPGetLadderProgress {
    @HttpGet
    global static void doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        String cpId = req.params.get('cpId');
        Map<String, Object> errorResult = new Map<String, Object>();
        if(String.isBlank(cpId)){
            errorResult.put('status', 'error');
            errorResult.put('message', 'Please pass valid CP Id');
            res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
            res.statusCode = 400;
        }else{
            try{
                list<Booking__c> blist = [Select id,Brokerage_Scheme__c,Status__c,Additional_Brokerage_Accrued_Dashboards__c,Base_Brokerage_Accrued_Dashboards__c from Booking__c where 
                                          BrokerIId__c =: cpId and Status__c = 'Booking Confirmed' and Source_of_Booking__c ='Channel Partner' and 
                                          Brokerage_Scheme__c != null order by CreatedDate desc];
                Map<String,list<Booking__c>> schIdVsBkMap = new Map<String,list<Booking__c>>();
                list<Brokerage_Slab__c> bslist = [Select Id,Name,Brokerage_Scheme__c,Brokerage_Scheme__r.Slab_Type__c,To__c,From__c,Brokerage_Scheme__r.Type__c,Total_Brokerage_for_Local_Bookings__c,Total_Brokerage_for_OS_NRI__c from Brokerage_Slab__c where Brokerage_Scheme__r.Approval_Status__c = 'Approved by Level 2' order by Brokerage_Scheme__c , From__c];
                list<Brokerage_scheme__c> bschlist =  [Select Id from Brokerage_Scheme__c where Approval_Status__c = 'Approved by Level 2' and Id ='a2aJ40000008kfWIAQ' order by createddate desc];
                Map<String,list<Brokerage_Slab__c>> schIdVsBrkSlabMap = new Map<String,list<Brokerage_Slab__c>>();
                for(Brokerage_Scheme__c bs :bschlist){
                    //Assign scheme vs Bookings in Map
                    schIdVsBkMap.put(bs.Id,new list<Booking__c>());  
                    schIdVsBrkSlabMap.put(bs.Id,new list<Brokerage_Slab__c>()); 
                    for(Booking__c b : blist){
                        if(b.Brokerage_Scheme__c == bs.Id){
                            schIdVsBkMap.get(bs.Id).add(b);
                        }
                    }
                    //Assigning scheme vs Brokerage Slabs Map
                    for(Brokerage_Slab__c br : bslist){
                        if(br.Brokerage_Scheme__c == bs.Id){
                            schIdVsBrkSlabMap.get(bs.Id).add(br);
                        }
                    }
                    
                }
                
                for(String key : schIdVsBkMap.keyset()){
                    system.debug('Bookings ->>>> '+ 'Key -> '+ key + ' Value -> '+schIdVsBkMap.get(key).size());
                    system.debug('Brokerage Slabs ->>>> '+ 'Key -> '+ key + ' Value -> '+schIdVsBrkSlabMap.get(key));                    
                    Decimal Earnedsofar = 0;
                    for(Booking__c b : schIdVsBkMap.get(key)){
                        Decimal TotalBrokerageEarned = (b.Base_Brokerage_Accrued_Dashboards__c != null ? b.Base_Brokerage_Accrued_Dashboards__c : 0) + (b.Additional_Brokerage_Accrued_Dashboards__c != null ? b.Additional_Brokerage_Accrued_Dashboards__c : 0);
                        Earnedsofar += TotalBrokerageEarned;
                        //system.debug('Base_Brokerage_Accrued_Dashboards__c -> '+b.Base_Brokerage_Accrued_Dashboards__c);
                        //system.debug('Additional_Brokerage_Accrued_Dashboards__c -> '+b.Additional_Brokerage_Accrued_Dashboards__c);
                    }
                    system.debug('Earned So Far ->>> '+Earnedsofar);
                    Brokerage_Slab__c currentSlab;
                    Brokerage_Slab__c nextSlab;
                    Brokerage_Slab__c topSlab = schIdVsBrkSlabMap.get(key)[schIdVsBrkSlabMap.get(key).size() - 1];
                    if(schIdVsBrkSlabMap.get(key)[0].Brokerage_Scheme__r.Slab_Type__c == 'Count'){                       
                        
                        for(Integer i = 0; i < schIdVsBrkSlabMap.get(key).size(); i++) {
                            Brokerage_Slab__c slab = schIdVsBrkSlabMap.get(key)[i];
                            
                            if(slab.From__c <= schIdVsBkMap.get(key).size() && (slab.To__c == null || slab.To__c >= schIdVsBkMap.get(key).size())) {
                                currentSlab = slab;
                                
                                if(i + 1 < schIdVsBrkSlabMap.get(key).size()) {
                                    nextSlab = schIdVsBrkSlabMap.get(key)[i + 1];
                                }
                                break;
                            }
                        }
                        
                        //Current Slab
                        Decimal currentSlabBrokerage;
                        if (currentSlab.Brokerage_Scheme__r.Type__c == 'Local') {
                            currentSlabBrokerage = currentSlab.Total_Brokerage_for_Local_Bookings__c;
                        } else if (currentSlab.Brokerage_Scheme__r.Type__c == 'NRI') {
                            currentSlabBrokerage = currentSlab.Total_Brokerage_for_OS_NRI__c;
                        } else if (currentSlab.Brokerage_Scheme__r.Type__c == 'Both') {
                            currentSlabBrokerage = (currentSlab.Total_Brokerage_for_Local_Bookings__c != null) ? currentSlab.Total_Brokerage_for_Local_Bookings__c : currentSlab.Total_Brokerage_for_OS_NRI__c;
                        }
                        
                        //Next Slab
                        Decimal nextSlabBrokerage;
                        if (nextSlab.Brokerage_Scheme__r.Type__c == 'Local') {
                            nextSlabBrokerage = nextSlab.Total_Brokerage_for_Local_Bookings__c;
                        } else if (nextSlab.Brokerage_Scheme__r.Type__c == 'NRI') {
                            nextSlabBrokerage = nextSlab.Total_Brokerage_for_OS_NRI__c;
                        } else if (nextSlab.Brokerage_Scheme__r.Type__c == 'Both') {
                            nextSlabBrokerage = (nextSlab.Total_Brokerage_for_Local_Bookings__c != null) ? nextSlab.Total_Brokerage_for_Local_Bookings__c : nextSlab.Total_Brokerage_for_OS_NRI__c;
                        }
                        
                        //Top Slab
                        Decimal topSlabBrokerage;
                        if (topSlab.Brokerage_Scheme__r.Type__c == 'Local') {
                            topSlabBrokerage = topSlab.Total_Brokerage_for_Local_Bookings__c;
                        } else if (topSlab.Brokerage_Scheme__r.Type__c == 'NRI') {
                            topSlabBrokerage = topSlab.Total_Brokerage_for_OS_NRI__c;
                        } else if (topSlab.Brokerage_Scheme__r.Type__c == 'Both') {
                            topSlabBrokerage = (topSlab.Total_Brokerage_for_Local_Bookings__c != null) ? topSlab.Total_Brokerage_for_Local_Bookings__c : topSlab.Total_Brokerage_for_OS_NRI__c;
                        }
                        
                        system.debug('Current :  ' + schIdVsBkMap.get(key).size() + ' Bookings - ' + currentSlabBrokerage + '% Brokerage');
                        system.debug('Next :  ' + 'Do ' + (nextSlab.From__c - schIdVsBkMap.get(key).size())  + ' more to reach ' + nextSlabBrokerage + '%');
                        system.debug('Top :  ' + 'Do ' + (topSlab.From__c - schIdVsBkMap.get(key).size())  + ' more to reach ' + topSlabBrokerage + '%');
	                        
                    }
                    if(schIdVsBrkSlabMap.get(key)[0].Brokerage_Scheme__r.Slab_Type__c == 'Value'){
                        Decimal totalAV = 0;
                        for(Booking__c b : schIdVsBkMap.get(key)){
                            totalAV += b.Agreement_Value_for_brokers__c;
                        }
                        
                        for(Integer i = 0; i < schIdVsBrkSlabMap.get(key).size(); i++) {
                            Brokerage_Slab__c slab = schIdVsBrkSlabMap.get(key)[i];
                            
                            if(slab.From__c <= totalAV  && (slab.To__c == null || slab.To__c >= totalAV)) {
                                currentSlab = slab;
                                
                                if(i + 1 < schIdVsBrkSlabMap.get(key).size()) {
                                    nextSlab = schIdVsBrkSlabMap.get(key)[i + 1];
                                }
                                break;
                            }
                        }
                        
                        //Current Slab
                        Decimal currentSlabBrokerage;
                        if (currentSlab.Brokerage_Scheme__r.Type__c == 'Local') {
                            currentSlabBrokerage = currentSlab.Total_Brokerage_for_Local_Bookings__c;
                        } else if (currentSlab.Brokerage_Scheme__r.Type__c == 'NRI') {
                            currentSlabBrokerage = currentSlab.Total_Brokerage_for_OS_NRI__c;
                        } else if (currentSlab.Brokerage_Scheme__r.Type__c == 'Both') {
                            currentSlabBrokerage = (currentSlab.Total_Brokerage_for_Local_Bookings__c != null) ? currentSlab.Total_Brokerage_for_Local_Bookings__c : currentSlab.Total_Brokerage_for_OS_NRI__c;
                        }
                        
                        //Next Slab
                        Decimal nextSlabBrokerage;
                        if (nextSlab.Brokerage_Scheme__r.Type__c == 'Local') {
                            nextSlabBrokerage = nextSlab.Total_Brokerage_for_Local_Bookings__c;
                        } else if (nextSlab.Brokerage_Scheme__r.Type__c == 'NRI') {
                            nextSlabBrokerage = nextSlab.Total_Brokerage_for_OS_NRI__c;
                        } else if (nextSlab.Brokerage_Scheme__r.Type__c == 'Both') {
                            nextSlabBrokerage = (nextSlab.Total_Brokerage_for_Local_Bookings__c != null) ? nextSlab.Total_Brokerage_for_Local_Bookings__c : nextSlab.Total_Brokerage_for_OS_NRI__c;
                        }
                        
                        //Top Slab
                        Decimal topSlabBrokerage;
                        if (topSlab.Brokerage_Scheme__r.Type__c == 'Local') {
                            topSlabBrokerage = topSlab.Total_Brokerage_for_Local_Bookings__c;
                        } else if (topSlab.Brokerage_Scheme__r.Type__c == 'NRI') {
                            topSlabBrokerage = topSlab.Total_Brokerage_for_OS_NRI__c;
                        } else if (topSlab.Brokerage_Scheme__r.Type__c == 'Both') {
                            topSlabBrokerage = (topSlab.Total_Brokerage_for_Local_Bookings__c != null) ? topSlab.Total_Brokerage_for_Local_Bookings__c : topSlab.Total_Brokerage_for_OS_NRI__c;
                        }
                        system.debug('Current :  ' + totalAV + ' Bookings - ' + currentSlabBrokerage + '% Brokerage');
                        system.debug('Next :  ' + 'Do ' + (nextSlab.From__c - totalAV)  + ' more to reach ' + nextSlabBrokerage + '%');
                        system.debug('Top :  ' + 'Do ' + (topSlab.From__c - totalAV)  + ' more to reach ' + topSlabBrokerage + '%');   
                    }
                }
                
            }catch(exception e){
                errorResult.put('status', 'error');
                errorResult.put('message', e.getMessage() + ';  ' + e.getStackTraceString());
                res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                res.statusCode = 500;
            }
            
        }
    }
    
    public class resWrapper{
        public list<LadderDetails> ladderDetails;
    }
    
    public class LadderDetails{
        public String schemeName;
        public String startDate;
        public String endDate;
        public String type;
        public list<BookingDetails> bookingDetails;
    }
    
    public class BookingDetails{
        public CustomerDetails customerDetails;
        public BookingSummary bookingSummary;
        public FinancialDetails financialDetails;
    }
    
    public class CustomerDetails{
        public String name;
        public String contactNo;
        public String emailId;
        public String coApplicantName;
    }
    
    public class BookingSummary{
        public String projectName;
        public String unit;
        public String bookingDate;
        public String bookingId;
        public String status;
    }
    
    public class FinancialDetails{
        public Decimal agreementValue;
        public Decimal percentagePaid;
        public String registrationStatus;
        public String brokerageStatus;///????
    }
        
}