force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Unit Booked</fullName>
            </value>
            <value>
                <fullName>Booking Received</fullName>
            </value>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>Booking Blocked</fullName>
            </value>
            <value>
                <fullName>Booking Registered</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Sent for Revision</fullName>
            </value>
            <value>
                <fullName>Cancellation Initiated</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Pending</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Ready</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled - Refunded</fullName>
            </value>
            <value>
                <fullName>Booking Received - Payment Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brokerage__c/Brokerage__c.object-meta.xml
<CustomObject>
    <label>Brokerage</label>
    <nameField>
        <label>Brokerage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokerages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brokerage__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Brokerages</relationshipLabel>
    <relationshipName>Brokerages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Brokerage_Type__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Type__c</fullName>
    <label>Brokerage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base Brokerage</fullName>
            </value>
            <value>
                <fullName>Additional Brokerage</fullName>
            </value>
            <value>
                <fullName>Retrofit Brokerage</fullName>
            </value>
            <value>
                <fullName>Cancellation Brokerage</fullName>
            </value>
            <value>
                <fullName>Manual Override Brokerage</fullName>
            </value>
            <value>
                <fullName>Source Change Brokerage Cancellation</fullName>
            </value>
            <value>
                <fullName>Kicker Incentive</fullName>
            </value>
            <value>
                <fullName>AOP Brokerage</fullName>
            </value>
            <value>
                <fullName>AOP Interim Brokerage</fullName>
            </value>
            <value>
                <fullName>AOP Final Brokerage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Brokerages</relationshipLabel>
    <relationshipName>Brokerages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Due</fullName>
            </value>
            <value>
                <fullName>Due</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/Brokerage_Invoice__c.object-meta.xml
<CustomObject>
    <label>Brokerage Invoice Line Item</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>Brokerage Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Brokerage_In_Rs__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_In_Rs__c</fullName>
    <label>Brokerage (In Rs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Brokerage_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Lookup__c</fullName>
    <label>Brokerage</label>
    <referenceTo>Brokerage__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>IF( CONTAINS(Booking__r.Primary_Applicant_Name__c, &apos;Mr.&apos;) , SUBSTITUTE(Booking__r.Primary_Applicant_Name__c
, &apos;Mr.&apos;, &apos;&apos;),IF( CONTAINS(Booking__r.Primary_Applicant_Name__c, &apos;Mrs.&apos;) , SUBSTITUTE(Booking__r.Primary_Applicant_Name__c
, &apos;Mrs.&apos;, &apos;&apos;),IF( CONTAINS(Booking__r.Primary_Applicant_Name__c, &apos;Ms.&apos;) , SUBSTITUTE(Booking__r.Primary_Applicant_Name__c
, &apos;Ms.&apos;, &apos;&apos;),IF( CONTAINS(Booking__r.Primary_Applicant_Name__c, &apos;M/S.&apos;) , SUBSTITUTE(Booking__r.Primary_Applicant_Name__c
, &apos;M/S.&apos;, &apos;&apos;),Booking__r.Primary_Applicant_Name__c))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Brokerage_Summary__r.Project__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/SAP_Document_No__c.field-meta.xml
<CustomField>
    <fullName>SAP_Document_No__c</fullName>
    <label>SAP Document No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>/*IF(AND(Total_Amount_Balance__c &lt;= 1 ,  Total_Amount_Balance__c &gt;= -1), &apos;Paid&apos;, &apos;Unpaid&apos;)*/


IF(AND(Total_Amount_Balance__c &lt;= 1), &apos;Paid&apos;, &apos;Unpaid&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Total_Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Agreement_Value__c</fullName>
    <label>Total Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <label>Total Amount Paid</label>
    <summarizedField>Brokerage_Receipt__c.Invoice_Amount__c</summarizedField>
    <summaryForeignKey>Brokerage_Receipt__c.Brokerage_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner New</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Channel_Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Lockated_GetCPBrokerageDetails.cls
@RestResource(urlMapping='/cpGetBrokerageDetails/*')
global without sharing class Lockated_GetCPBrokerageDetails {
    @HttpGet
    global static void doGet() {
       RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        String cpId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        Map<String, Object> errorResult = new Map<String, Object>();
        if(String.isBlank(cpId)){
            errorResult.put('status', 'error');
            errorResult.put('message', 'Please pass valid CP Id');
            res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
            res.statusCode = 400;
        }else{
            try{
                ResponseWrapper resp = new ResponseWrapper();
                list<InvDetails> blist = new list<InvDetails>();
                list<InvDetails> llist = new list<InvDetails>();
                list<InvDetails> alist = new list<InvDetails>();
                Details details = new Details();
                Decimal totalPaid = 0;
                Decimal Base = 0;
                Decimal Ladder = 0;
                Decimal AOP = 0;
                list<Brokerage_Invoice__c> invlist = [Select id,Booking__c,Invoice_Amount__c,Total_Amount_Paid__c,Brokerage_Lookup__r.Brokerage_Type__c,
                                                      Customer_Name__c,Project__c,Total_Agreement_Value__c,Brokerage_In_Rs__c,Invoice_Date__c,Invoice_Number__c                                                   
                                                      from Brokerage_Invoice__c  where Channel_Partner__c =: cpId and Status__c = 'Paid' and SAP_Document_No__c != null];
                if(!invlist.isEmpty()){                    
                    for(Brokerage_Invoice__c i : invlist){
                        InvDetails b = new InvDetails();
                        InvDetails l = new InvDetails();
                        InvDetails a = new InvDetails();
                        totalPaid += i.Total_Amount_Paid__c;
                        if(i.Brokerage_Lookup__r.Brokerage_Type__c == 'Base Brokerage'){                            
                            assignInvDetails(b,i);
                            blist.add(b);          
                            
                            Base += i.Total_Amount_Paid__c;
                        } else if(i.Brokerage_Lookup__r.Brokerage_Type__c == 'Additional Brokerage'){
                            assignInvDetails(l,i);
                            llist.add(l);  
                            
                            Ladder += i.Total_Amount_Paid__c;
                        } 
                    }
                    system.debug('blist - '+blist);
                    system.debug('llist - '+llist);
                    details.BaseDetails = blist;
                    details.LadderDetails = llist;
                    resp.totalPaid = totalPaid;
                    resp.Base = Base;
                    resp.Ladder = Ladder;
                    resp.AOP = AOP;
                    resp.details = details;
                    res.responseBody = Blob.valueOf(JSON.serialize(resp));
                    res.statusCode = 200;
                }
                
              
            }catch(exception e){
                errorResult.put('status', 'error');
                errorResult.put('message', e.getMessage() + ';  ' + e.getStackTraceString());
                res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                res.statusCode = 400;
            }
            
        }
    }
    
    private static void assignInvDetails(InvDetails i, Brokerage_Invoice__c b){
        i.customerName = b.Customer_Name__c;
        i.projectName = b.Project__c;
        i.avValueForBrokerage = b.Total_Agreement_Value__c;
        i.brokerageAmount = b.Brokerage_In_Rs__c;
        i.paidDate = b.Invoice_Date__c;
        i.invoiceNo = b.Invoice_Number__c;
        i.statementUrl = null;
    }
    
    global class ResponseWrapper {
        public decimal invoiceStatus;
        public decimal totalPaid;
        public decimal base;
        public decimal ladder;
        public decimal aop;
        public Details details;        
    }
    
    public class Details{
        public list<InvDetails> BaseDetails;
        public list<InvDetails> LadderDetails;
        public list<InvDetails> AOPDetails;
    }
    
    public class InvDetails{
        public String customerName;
        public String projectName;
        public Decimal avValueForBrokerage;
        public Decimal brokerageAmount;
        public Date paidDate;
        public String invoiceNo;
        public String statementUrl;
    }
    
    
    public class Ladder{
        public String ladderSchemeName;
        public String projectName;
        public String startDate;
        public String endDate;
        public String bookingsEligible;
        public Decimal brokerageAmount;
        public Date paidDate;
        public String statementUrl;
    }
    
    public class AOP{
        public String fyOfAopScheme;
        public String aopAmount;
        public String achievedRevenue;
        public String runwalEntity;
        public String avForBrokerageInEntity;
        public String brokerageAmount;
        public Date paidDate;
        public String statementUrl;
    }
    
}