force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <label>Booking Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Runwal Bliss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker__c/fields/RW_Email__c.field-meta.xml
<CustomField>
    <fullName>RW_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Broker__c/fields/RW_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>RW_Mobile_No__c</fullName>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Proposed_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Visit_Date__c</fullName>
    <label>Proposed Visit Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RW_Broker__c.field-meta.xml
<CustomField>
    <fullName>RW_Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.LeadSource</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.LeadSource</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RW_Project__c.field-meta.xml
<CustomField>
    <fullName>RW_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please Select an Active Project</errorMessage>
        <filterItems>
            <field>Project__c.RW_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Walkin_Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Walkin_Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Walkin Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Leads (Walkin Channel Partner)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Walkin_Source__c.field-meta.xml
<CustomField>
    <fullName>Walkin_Source__c</fullName>
    <label>Walkin Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Employee / Managemen</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Exhibitions</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>Individual calling</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Magazines</fullName>
            </value>
            <value>
                <fullName>Newspapers</fullName>
            </value>
            <value>
                <fullName>NRI</fullName>
            </value>
            <value>
                <fullName>Outstation</fullName>
            </value>
            <value>
                <fullName>Paper Inserts</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Property Portals</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Surround Marketing</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Zee Marathi TVC</fullName>
            </value>
            <value>
                <fullName>R Circle Caller</fullName>
            </value>
            <value>
                <fullName>Temp Channel Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Visit__c</fullName>
    <label>Date Of Visit</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Broker__c.field-meta.xml
<CustomField>
    <fullName>RW_Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.LeadSource</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.LeadSource</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Email__c.field-meta.xml
<CustomField>
    <fullName>RW_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>RW_Mobile_No__c</fullName>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Project__c.field-meta.xml
<CustomField>
    <fullName>RW_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Walkin_Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>RW_Walkin_Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Walkin Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Walkin_Source__c</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Temp Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.Walkin_Source__c</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <filterItems>
            <field>Broker__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Opportunities (Walkin Channel Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Walkin_Source__c.field-meta.xml
<CustomField>
    <fullName>Walkin_Source__c</fullName>
    <label>Walkin Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Employee / Managemen</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Exhibitions</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>Individual calling</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Magazines</fullName>
            </value>
            <value>
                <fullName>Newspapers</fullName>
            </value>
            <value>
                <fullName>NRI</fullName>
            </value>
            <value>
                <fullName>Outstation</fullName>
            </value>
            <value>
                <fullName>Paper Inserts</fullName>
            </value>
            <value>
                <fullName>PreSales</fullName>
            </value>
            <value>
                <fullName>Property Portals</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>R Circle Caller</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Surround Marketing</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Zee Marathi TVC</fullName>
            </value>
            <value>
                <fullName>Temp Channel Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Lockated_CPGetMyLeads.cls
@RestResource(urlMapping='/cpGetMyLeads/*')
global without sharing class Lockated_CPGetMyLeads {
    
    @HttpGet
    global static void doGet() {
       RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        String cpId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        Map<String, Object> errorResult = new Map<String, Object>();
        if(String.isBlank(cpId)){
            errorResult.put('status', 'error');
            errorResult.put('message', 'Please pass valid CP Id');
            res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
            res.statusCode = 400;
        }else{
            try{
                ResponseWrapper resp = new ResponseWrapper();
                Id CPRecordTypeId = Schema.SObjectType.Broker__c.getRecordTypeInfosByName().get('Channel Partner').getRecordTypeId();
                Id TempCPRecordTypeId = Schema.SObjectType.Broker__c.getRecordTypeInfosByName().get('Temp Channel Partner').getRecordTypeId();                
                list<Broker__c> brlist = [Select Id,RecordTypeId from Broker__c where Id =: cpId];
                if(!brlist.isEmpty()){
                    list<LeadDetails> ActiveLeadDetailslist = new list<LeadDetails>();
                    list<LeadDetails> InactiveLeadDetailslist = new list<LeadDetails>();
                    list<SiteVisitDetails> SiteVisitDetailslist = new list<SiteVisitDetails>();
                    list<BookingDetails> BookingDetailslist = new list<BookingDetails>();
                    if(brlist[0].RecordTypeId == CPRecordTypeId){
                        //Active and Inactive Leads
                        list<lead> leadlist = [Select Id,Name,RW_Mobile_No__c,Email,RW_Project__c,RW_Project__r.Name,Proposed_Visit_Date__c,IsActive__c FROM Lead where 
                                               (Walkin_Channel_Partner__c = :cpId OR RW_Broker__c =: cpId)
                                               AND (LeadSource = 'Channel Partner' OR Walkin_Source__c = 'Channel Partner') ];
                        if(!leadlist.isEmpty()){
                            for(Lead l1 : leadlist ){
                                if(l1.IsActive__c){
                                    LeadDetails l = new LeadDetails();
                                    l.name = l1.Name;
                                    l.mobile = l1.RW_Mobile_No__c;
                                    l.email = l1.Email;
                                    l.project = l1.RW_Project__r.Name;
                                    l.siteVisitDate = Date.valueof(l1.Proposed_Visit_Date__c);
                                    ActiveLeadDetailslist.add(l);
                                }else{
                                    LeadDetails l = new LeadDetails();
                                    l.name = l1.Name;
                                    l.mobile = l1.RW_Mobile_No__c;
                                    l.email = l1.Email;
                                    l.project = l1.RW_Project__r.Name;
                                    l.siteVisitDate = Date.valueof(l1.Proposed_Visit_Date__c);
                                    InactiveLeadDetailslist.add(l);
                                }
                                
                            }
                        }
                        
                        //Site Visits
                        list<Opportunity> opplist = [Select Id,Name,StageName,RW_Mobile_No__c,RW_Email__c,RW_Project__r.Name,Date_Of_Visit__c FROM Opportunity where
                                                     RW_Walkin_Channel_Partner__c  = : cpId 
                                                     AND Walkin_Source__c  = 'Channel Partner'
                                                     AND StageName = 'Site Visit'];
                        if(!opplist.isEmpty()){
                            for(Opportunity o : opplist ){
                                SiteVisitDetails sv = new SiteVisitDetails();
                                sv.oppId = o.id;
                                sv.status = o.StageName;
                                sv.name = o.Name;
                                sv.mobile = o.RW_Mobile_No__c;
                                sv.email = o.RW_Email__c;
                                sv.project = o.RW_Project__r.Name;
                                sv.siteVisitDate = o.Date_Of_Visit__c;
                                SiteVisitDetailslist.add(sv);
                            }
                        }
                        
                        //Bookings
                        list<Booking__c> blist = [SELECT Id,Name,Booking_Date__c,Source_of_Booking__c,Status__c,Project__r.Name,Opportunity__r.Name
                                                     FROM Booking__c where 
                                                     Source_of_Booking__c ='Channel Partner'  and BrokerIId__c =: cpId Order by CreatedDate Desc];
                        if(!blist.isEmpty()){
                            for(Booking__c b1 : blist ){
                                BookingDetails b = new BookingDetails();
                                b.bookingId = b1.id;
                                b.status = b1.Status__c;
                                b.bookingdate = Date.valueof(b1.Booking_Date__c);
                                b.project = b1.Project__r.Name;
                                BookingDetailslist.add(b);
                            }
                        }
                        
                        
                        
                    } else if(brlist[0].RecordTypeId == TempCPRecordTypeId){
                        //Active and Inactive Leads
                        list<lead> leadlist = [Select Id,Name,RW_Mobile_No__c,Email,RW_Project__c,RW_Project__r.Name,Proposed_Visit_Date__c,IsActive__c FROM Lead where 
                                               (Walkin_Channel_Partner__c = :cpId OR RW_Broker__c =: cpId)
                                               AND (LeadSource = 'Temp Channel Partner' OR Walkin_Source__c = 'Temp Channel Partner')];
                        if(!leadlist.isEmpty()){
                            for(Lead l1 : leadlist ){
                                if(l1.IsActive__c){
                                    LeadDetails l = new LeadDetails();
                                    l.name = l1.Name;
                                    l.mobile = l1.RW_Mobile_No__c;
                                    l.email = l1.Email;
                                    l.project = l1.RW_Project__r.Name;
                                    l.siteVisitDate = Date.valueof(l1.Proposed_Visit_Date__c);
                                    ActiveLeadDetailslist.add(l);
                                }else{
                                    LeadDetails l = new LeadDetails();
                                    l.name = l1.Name;
                                    l.mobile = l1.RW_Mobile_No__c;
                                    l.email = l1.Email;
                                    l.project = l1.RW_Project__r.Name;
                                    l.siteVisitDate = Date.valueof(l1.Proposed_Visit_Date__c);
                                    InactiveLeadDetailslist.add(l);
                                }
                            }
                        }
                        
                        //Site Visits
                        list<Opportunity> opplist = [Select Id,Name,StageName,RW_Mobile_No__c,RW_Email__c,RW_Project__r.Name,Date_Of_Visit__c FROM Opportunity where
                                                     RW_Walkin_Channel_Partner__c  = : cpId 
                                                     AND Walkin_Source__c  = 'Temp Channel Partner'
                                                     AND StageName = 'Site Visit'];
                        if(!opplist.isEmpty()){
                            for(Opportunity o : opplist ){
                                SiteVisitDetails sv = new SiteVisitDetails();
                                sv.oppId = o.id;
                                sv.status = o.StageName;
                                sv.name = o.Name;
                                sv.mobile = o.RW_Mobile_No__c;
                                sv.email = o.RW_Email__c;
                                sv.project = o.RW_Project__r.Name;
                                sv.siteVisitDate = o.Date_Of_Visit__c;
                                SiteVisitDetailslist.add(sv);
                            }
                        }
                        
                        //Bookings
                        list<Booking__c> blist = [SELECT Id,Name,Booking_Date__c,Source_of_Booking__c,Status__c,Project__r.Name,Opportunity__r.Name
                                                     FROM Booking__c where 
                                                     Source_of_Booking__c ='Temp Channel Partner'  and BrokerIId__c =: cpId Order by CreatedDate Desc];
                        if(!blist.isEmpty()){
                            for(Booking__c b1 : blist ){
                                BookingDetails b = new BookingDetails();
                                b.bookingId = b1.id;
                                b.status = b1.Status__c;
                                b.bookingdate = Date.valueof(b1.Booking_Date__c);
                                b.project = b1.Project__r.Name;
                                BookingDetailslist.add(b);
                            }
                        }
                    }
                    
                    resp.activeLeadDetails = ActiveLeadDetailslist;
                    resp.inactiveLeadDetails = InactiveLeadDetailslist;
                    resp.siteVisitDetails = SiteVisitDetailslist;
                    resp.bookingDetails = BookingDetailslist;
                    res.responseBody = Blob.valueOf(JSON.serialize(resp));
                    res.statusCode = 200;
                }else{
                    errorResult.put('status', 'error');
                    errorResult.put('message', 'No CP found with this ID');
                    res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                    res.statusCode = 400;
                }
                //return details;
                res.responseBody = Blob.valueOf(JSON.serialize(resp));
                res.statusCode = 200;
            }catch(exception e){
                errorResult.put('status', 'error');
                errorResult.put('message', e.getMessage() + ';  ' + e.getStackTraceString());
                res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                res.statusCode = 400;
            }
            
        }
    }
    
    global class ResponseWrapper {
        public list<LeadDetails> activeLeadDetails;
        public list<LeadDetails> inactiveLeadDetails;
        public list<SiteVisitDetails> siteVisitDetails;
        public list<BookingDetails> bookingDetails;
    }
    
    public class LeadDetails{
        public String name;
        public String mobile;
        public String email;
        public String project;
        public Date siteVisitDate;
        public String inviteCode;//Clearify Needed.
    }
    
    
    public class SiteVisitDetails{
        public String oppId;
        public String status;
        public String name;
        public String mobile;
        public String email;
        public String project;
        public Date siteVisitDate;
    }
    
    public class BookingDetails{
        public String bookingId;
        public String project;
        public Date bookingdate;
        public String status;
    }
    
}