force-app/main/default/objects/Account/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Query_Config__mdt/Batch_Query_Config__mdt.object-meta.xml
<CustomObject>
    <label>Batch Query Config</label>
    <pluralLabel>Batch Query Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Batch_Query_Config__mdt/fields/SOQL_Query__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Query__c</fullName>
    <label>SOQL Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/CP_Invoice_Clearing_L1__c.field-meta.xml
<CustomField>
    <fullName>CP_Invoice_Clearing_L1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Invoice Clearing L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/CP_Invoice_Clearing_L2__c.field-meta.xml
<CustomField>
    <fullName>CP_Invoice_Clearing_L2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Invoice Clearing L2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Old_Booking__c.field-meta.xml
<CustomField>
    <fullName>Old_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage__c/Brokerage__c.object-meta.xml
<CustomObject>
    <label>Brokerage</label>
    <nameField>
        <label>Brokerage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokerages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brokerage__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Brokerages</relationshipLabel>
    <relationshipName>Brokerages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Brokerage_Type__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Type__c</fullName>
    <label>Brokerage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base Brokerage</fullName>
            </value>
            <value>
                <fullName>Additional Brokerage</fullName>
            </value>
            <value>
                <fullName>Retrofit Brokerage</fullName>
            </value>
            <value>
                <fullName>Cancellation Brokerage</fullName>
            </value>
            <value>
                <fullName>Manual Override Brokerage</fullName>
            </value>
            <value>
                <fullName>Source Change Brokerage Cancellation</fullName>
            </value>
            <value>
                <fullName>Kicker Incentive</fullName>
            </value>
            <value>
                <fullName>AOP Brokerage</fullName>
            </value>
            <value>
                <fullName>AOP Interim Brokerage</fullName>
            </value>
            <value>
                <fullName>AOP Final Brokerage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipLabel>Brokerages</relationshipLabel>
    <relationshipName>Brokerages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage__c/fields/Total_Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Total_Brokerage__c</fullName>
    <formula>Brokerage__c -  Cancelled_Brokerage_percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Brokerage %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/Brokerage_Invoice__c.object-meta.xml
<CustomObject>
    <label>Brokerage Invoice Line Item</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>Brokerage Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Brokerage_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Lookup__c</fullName>
    <label>Brokerage</label>
    <referenceTo>Brokerage__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active Channel Partner</errorMessage>
        <filterItems>
            <field>Broker__c.Deactivated__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/CP_Brokerage__c.field-meta.xml
<CustomField>
    <fullName>CP_Brokerage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Brokerage</label>
    <referenceTo>CP_Brokerage__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/CP_Invoice_Clearing_L1__c.field-meta.xml
<CustomField>
    <fullName>CP_Invoice_Clearing_L1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Invoice Clearing L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Brokerage_Invoices5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brokerage_Invoice__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipName>Brokerage_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner New</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Channel_Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Brokerage__c/CP_Brokerage__c.object-meta.xml
<CustomObject>
    <label>CP Brokerage Invoices</label>
    <nameField>
        <displayFormat>CPB-{0000}</displayFormat>
        <label>CP Brokerage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Brokerage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Brokerage__c/fields/Brokerage_Type__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Type__c</fullName>
    <label>Brokerage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base Brokerage</fullName>
            </value>
            <value>
                <fullName>Additional Brokerage</fullName>
            </value>
            <value>
                <fullName>AOP Brokerage</fullName>
            </value>
            <value>
                <fullName>AOP Final Brokerage</fullName>
            </value>
            <value>
                <fullName>AOP Interim Brokerage</fullName>
            </value>
            <value>
                <fullName>Kicker Incentive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Brokerage__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Broker__c</referenceTo>
    <relationshipName>CP_Brokerage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Brokerage__c/fields/CP_Invoice_Clearing_L1__c.field-meta.xml
<CustomField>
    <fullName>CP_Invoice_Clearing_L1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Invoice Clearing L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CP_Brokerage5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Brokerage__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipName>CP_Brokerage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Brokerage__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CP_Brokerage__c/fields/Total_Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Total_Brokerage__c</fullName>
    <label>Total Brokerage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MonthwiseBrokerageRecords.cls
public class MonthwiseBrokerageRecords implements Database.Batchable<SObject>, Database.Stateful {

private Integer processedInvoices = 0;
private Integer createdCPBrokerages = 0;
private List<String> errorMessages = new List<String>();

public Database.QueryLocator start(Database.BatchableContext bc) {
    System.debug('=== MONTHWISE BROKERAGE RECORDS BATCH START ===');
    System.debug('Processing Current Month Invoices');
    // Fetch metadata record
    Batch_Query_Config__mdt config = [
        SELECT SOQL_Query__c
        FROM Batch_Query_Config__mdt
        WHERE DeveloperName = 'QueryForMonthwiseBrokerageInvoice'
        LIMIT 1
    ];        
        String query = config != null && String.isNotBlank(config.SOQL_Query__c)
                ? config.SOQL_Query__c
                : 'SELECT Id, Booking__c, Booking__r.Tower__r.Legal_Entity__c, ' +
                    'Channel_Partner__c, Invoice_Amount__c, CreatedDate, ' +
                    'Brokerage_Lookup__r.Name, ' +
                    'Booking__r.Name, Channel_Partner__r.Name ' +
                    'FROM Brokerage_Invoice__c ' +
                    'WHERE Brokerage_Lookup__r.Name = \'Additional Brokerage\' ' +
                    'AND CreatedDate = THIS_MONTH ' +
                    'AND Booking__r.Tower__r.Legal_Entity__c != null ' +
                    'AND Channel_Partner__c != null ' +
                    'AND CP_Brokerage__c = null';

System.debug('Query from Metadata: ' + query);

return Database.getQueryLocator(query);
}

public void execute(Database.BatchableContext bc, List<Brokerage_Invoice__c> invoices) {
    System.debug('=== EXECUTE METHOD START ===');
    System.debug('Processing ' + invoices.size() + ' invoices in this batch');
    
    if (invoices.isEmpty()) {
        System.debug('No invoices to process in this batch');
        return;
    }
    
    try {
        Map<String, GroupedInvoiceData> groupedData = new Map<String, GroupedInvoiceData>();
        
        for (Brokerage_Invoice__c inv : invoices) {
            String legalEntityId = inv.Booking__r.Tower__r.Legal_Entity__c;
            String channelPartnerId = inv.Channel_Partner__c;
            String groupKey = legalEntityId + '-' + channelPartnerId;
            
            if (!groupedData.containsKey(groupKey)) {
                groupedData.put(groupKey, new GroupedInvoiceData(legalEntityId, channelPartnerId));
            }
            
            GroupedInvoiceData data = groupedData.get(groupKey);
            data.addInvoice(inv);
            
            System.debug('Invoice ' + inv.Id + ' | Amount: ' + inv.Invoice_Amount__c + 
                            ' | CP: ' + inv.Channel_Partner__r.Name + 
                            ' | Booking: ' + inv.Booking__r.Name);
        }
        
        System.debug('Grouped into ' + groupedData.size() + ' Legal Entity-CP combinations');
        
        List<CP_Brokerage__c> cpBrokerageRecords = new List<CP_Brokerage__c>();
        
        Date today = System.today();
        String currentMonthString = today.year() + '-' + String.valueOf(today.month()).leftPad(2, '0');
        
        for (String groupKey : groupedData.keySet()) {
            GroupedInvoiceData data = groupedData.get(groupKey);
            
            CP_Brokerage__c cpBrokerage = new CP_Brokerage__c(
                Legal_Entity__c = data.legalEntityId,
                Channel_Partner__c = data.channelPartnerId,
                Month__c = currentMonthString, 
                Total_Brokerage__c = data.totalAmount,
                Brokerage_Type__c='Additional Brokerage',
                CP_Invoice_Clearing_L1__c = invoices[0].CP_Invoice_Clearing_L1__c,
                CP_Invoice_Clearing_L2__c = invoices[0].CP_Invoice_Clearing_L1__c,

                CP_Invoice_Approver_L1__c = invoices[0].CP_Invoice_Approver_L2__c,
                CP_Invoice_Approver_L2__c = invoices[0].CP_Invoice_Approver_L3__c,
                CP_Invoice_Approver_L3__c = invoices[0].CP_Invoice_Approver_L4__c,
                CP_Invoice_Approver_L4__c = invoices[0].CP_Invoice_Approver_L5__c,
                CP_MIS__c = invoices[0].CP_Invoice_Approver_L1__c

            );
            
            cpBrokerageRecords.add(cpBrokerage);
            
            System.debug('Creating CP_Brokerage: Legal Entity=' + data.legalEntityId + 
                            ' | CP=' + data.channelPartnerId + 
                            ' | Month=' + currentMonthString +
                            ' | Total=' + data.totalAmount + 
                            ' | Count=' + data.invoiceIds.size());
        }
        
        if (!cpBrokerageRecords.isEmpty()) {
            insert cpBrokerageRecords;
            createdCPBrokerages += cpBrokerageRecords.size();
            System.debug('Successfully inserted ' + cpBrokerageRecords.size() + ' CP_Brokerage records');
        }
        
        List<Brokerage_Invoice__c> invoicesToUpdate = new List<Brokerage_Invoice__c>();
        Integer recordIndex = 0;
        
        for (String groupKey : groupedData.keySet()) {
            GroupedInvoiceData data = groupedData.get(groupKey);
            CP_Brokerage__c cpBrokerage = cpBrokerageRecords[recordIndex++];
            
            for (Id invoiceId : data.invoiceIds) {
                invoicesToUpdate.add(new Brokerage_Invoice__c(
                    Id = invoiceId,
                    CP_Brokerage__c = cpBrokerage.Id
                ));
            }
        }
        
        if (!invoicesToUpdate.isEmpty()) {
            update invoicesToUpdate;
            processedInvoices += invoicesToUpdate.size();
            System.debug('Successfully updated ' + invoicesToUpdate.size() + ' invoices with CP_Brokerage links');
        }
        
    } catch (Exception e) {
        String errorMsg = 'Error in execute method: ' + e.getMessage() + ' | Line: ' + e.getLineNumber();
        System.debug('ERROR: ' + errorMsg);
        errorMessages.add(errorMsg);
        throw e; 
    }
    
    System.debug('=== EXECUTE METHOD END ===');
}

public void finish(Database.BatchableContext bc) {
    System.debug('=== MONTHWISE BROKERAGE BATCH FINISH ===');
    
    // Get job statistics
    AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, 
                        TotalJobItems, CompletedDate, ExtendedStatus
                        FROM AsyncApexJob WHERE Id = :bc.getJobId()];
    
    System.debug('Job Status: ' + job.Status);
    System.debug('Processed: ' + job.JobItemsProcessed + '/' + job.TotalJobItems);
    System.debug('Errors: ' + job.NumberOfErrors);
    System.debug('Extended Status: ' + job.ExtendedStatus);
    System.debug('Completed: ' + job.CompletedDate);
    
    // Custom statistics
    System.debug('=== PROCESSING SUMMARY ===');
    Date today = System.today();
    // String currentMonth = today.format('MMMM yyyy');
    //    /    System.debug('Processed Month: ' + currentMonth + ' (' + today.year() + '-' + String.valueOf(today.month()).leftPad(2, '0') + ')');
    System.debug('Total Invoices Processed: ' + processedInvoices);
    System.debug('CP_Brokerage Records Created: ' + createdCPBrokerages);
    System.debug('Error Count: ' + errorMessages.size());
    
    if (!errorMessages.isEmpty()) {
        System.debug('=== ERRORS ENCOUNTERED ===');
        for (String error : errorMessages) {
            System.debug('ERROR: ' + error);
        }
    }
    
    // Optional: Send email notification
    if (job.Status == 'Completed' && job.NumberOfErrors == 0) {
        System.debug('SUCCESS: Monthwise brokerage batch completed successfully!');
        // sendSuccessEmail();
    } else {
        System.debug('WARNING: Monthwise brokerage batch completed with errors or failures');
        // sendErrorEmail(job, errorMessages);
    }
    
    System.debug('=== BATCH PROCESSING COMPLETE ===');
}

// Helper class to group invoice data
private class GroupedInvoiceData {
    public String legalEntityId;
    public String channelPartnerId;
    public Decimal totalAmount = 0;
    public List<Id> invoiceIds = new List<Id>();
    public Integer invoiceCount = 0;
    
    public GroupedInvoiceData(String legalEntity, String channelPartner) {
        this.legalEntityId = legalEntity;
        this.channelPartnerId = channelPartner;
    }
    
    public void addInvoice(Brokerage_Invoice__c invoice) {
        this.totalAmount += (invoice.Invoice_Amount__c ?? 0);
        this.invoiceIds.add(invoice.Id);
        this.invoiceCount++;
    }
}

// Optional email notification methods
private void sendSuccessEmail() {
    // Implementation for success notification
    System.debug('Sending success notification email...');
}

private void sendErrorEmail(AsyncApexJob job, List<String> errors) {
    // Implementation for error notification
    System.debug('Sending error notification email...');
}
}