force-app/main/default/objects/Account/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <formula>(&quot;XXXXX&quot;&amp;right(Mobile_No__c,5))</formula>
    <label>Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <formula>(&quot;XXXXX&quot;&amp;right(RW_Mobile_No__c,5))</formula>
    <label>Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Web To Lead Project</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <formula>(&quot;XXXXX&quot;&amp;right(RW_Mobile_No__c,5))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Schedule_SMS_c__c/SMS_Schedule_SMS_c__c.object-meta.xml
<CustomObject>
    <label>SMS Schedule SMS</label>
    <nameField>
        <label>SMS Schedule SMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Schedule SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Schedule_SMS_c__c/fields/Lead_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Lead_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Lookup</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>SMS Schedule SMS</relationshipLabel>
    <relationshipName>SMS_Schedule_SMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Schedule_SMS_c__c/fields/Message_Sent_from_SFMC__c.field-meta.xml
<CustomField>
    <fullName>Message_Sent_from_SFMC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Message Sent from SFMC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_Schedule_SMS_c__c/fields/Opportunity_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Lookup</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SMS Schedule SMS</relationshipLabel>
    <relationshipName>SMS_Schedule_SMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Schedule_SMS_c__c/fields/Sender_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Sender_Mobile__c</fullName>
    <label>Sender Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SMS_Schedule_SMS_c__c/fields/SMS_Long_text__c.field-meta.xml
<CustomField>
    <fullName>SMS_Long_text__c</fullName>
    <label>SMS Long text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message_Status__c/WhatsApp_Message_Status__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Message Status</label>
    <nameField>
        <displayFormat>WMS-{00000}</displayFormat>
        <label>WhatsApp Message Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Message Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsApp_Message_Status__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WhatsApp Message Statuses</relationshipLabel>
    <relationshipName>WhatsApp_Message_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message_Status__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>WhatsApp Message Statuses</relationshipLabel>
    <relationshipName>WhatsApp_Message_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message_Status__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>WhatsApp Message Statuses</relationshipLabel>
    <relationshipName>WhatsApp_Message_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message_Status__c/fields/Message_Sent_from_SFMC__c.field-meta.xml
<CustomField>
    <fullName>Message_Sent_from_SFMC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Message Sent from SFMC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>WhatsApp Message Statuses</relationshipLabel>
    <relationshipName>WhatsApp_Message_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SMS_WhatsAppMessage_Status_Webhook_SFMC.cls
@RestResource(urlMapping='/messageStatusWebhook/*')
global class SMS_WhatsAppMessage_Status_Webhook_SFMC {

    @HttpPost
    global static void doPost(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        Map<String, Object> errorResult = new Map<String, Object>();
        String sObjName;
        try{
            system.debug('req: ' + req.requestBody);
            String jsonBody = req.requestBody.toString();
            system.debug('jsonBody: ' + jsonBody);
            RespDetails resData = (RespDetails)JSON.deserialize(jsonBody, RespDetails.class);
            if(resData.recordId != null){
                Id objId  = resData.recordId;
                sObjName = objId.getSObjectType().getDescribe().getName();
                
            }
            if(resData.messageType == 'SMS'){
                SMS_Schedule_SMS_c__c sms = new SMS_Schedule_SMS_c__c();
                sms.Status__c = resData.status;
                sms.Sender_Mobile__c = resData.mobile;
                sms.SMS_Long_text__c = resData.message;
                sms.Message_Sent_from_SFMC__c = true;
                if(sObjName == 'Opportunity'){
                    sms.Opportunity_Lookup__c = resData.recordId;
                }else if(sObjName == 'Lead'){
                    sms.Lead_Lookup__c = resData.recordId;
                }
                insert sms;
            }else if(resData.messageType == 'Whatsapp'){
                WhatsApp_Message_Status__c whatsapp = new WhatsApp_Message_Status__c();
                whatsapp.Status__c = resData.status;
                whatsapp.Mobile_Number__c = resData.mobile;
                whatsapp.Message__c = resData.message;
                whatsapp.Message_Sent_from_SFMC__c = true;
                if(sObjName == 'Opportunity'){
                    whatsapp.Opportunity__c = resData.recordId;
                }else if(sObjName == 'Case'){
                    whatsapp.Case__c = resData.recordId;
                }else if(sObjName == 'Account'){
                    whatsapp.Account__c = resData.recordId;
                }else if(sObjName == 'Lead'){
                    whatsapp.Lead__c = resData.recordId;
                }
                insert whatsapp;
            }
            res.responseBody = Blob.valueOf(JSON.serialize(resData));
            res.statusCode = 200;
        }catch(exception e){
            errorResult.put('status', 'error');
            errorResult.put('message', e.getMessage() + ';  ' + e.getStackTraceString());
            res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
            res.statusCode = 400;
        }
    }
    
    global class RespDetails{
        public String mobile;
        public String status;
        public String recordId;
        public String messageType;
        public String message;
    }
}