force-app/main/default/objects/Account/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <label>Mobile No</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/RW_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>RW_Mobile_No__c</fullName>
    <label>Mobile No.(TEXT)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Booking confirmed, Closed Lost</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking (Opportunity)</relationshipLabel>
    <relationshipName>Booking1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RW_Location__c.field-meta.xml
<CustomField>
    <fullName>RW_Location__c</fullName>
    <label>Preferred Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airoli</fullName>
            </value>
            <value>
                <fullName>Ambernath</fullName>
            </value>
            <value>
                <fullName>Andheri</fullName>
            </value>
            <value>
                <fullName>Antop Hill</fullName>
            </value>
            <value>
                <fullName>Badlapur</fullName>
                <label>BADLAPUR</label>
            </value>
            <value>
                <fullName>Bandra</fullName>
            </value>
            <value>
                <fullName>Bhandup</fullName>
            </value>
            <value>
                <fullName>Borivali</fullName>
            </value>
            <value>
                <fullName>Byculla</fullName>
            </value>
            <value>
                <fullName>CBD Belapur</fullName>
            </value>
            <value>
                <fullName>Chembur</fullName>
            </value>
            <value>
                <fullName>Churchagte</fullName>
            </value>
            <value>
                <fullName>Colaba</fullName>
            </value>
            <value>
                <fullName>Cuffe Parade</fullName>
            </value>
            <value>
                <fullName>Dadar</fullName>
            </value>
            <value>
                <fullName>Dahisar</fullName>
            </value>
            <value>
                <fullName>Dombivali</fullName>
            </value>
            <value>
                <fullName>Fort</fullName>
            </value>
            <value>
                <fullName>Ghansoli</fullName>
            </value>
            <value>
                <fullName>Ghatkopar</fullName>
            </value>
            <value>
                <fullName>Goregaon</fullName>
            </value>
            <value>
                <fullName>Govandi</fullName>
            </value>
            <value>
                <fullName>Jogeshwari</fullName>
            </value>
            <value>
                <fullName>Juhu</fullName>
            </value>
            <value>
                <fullName>Juinagar</fullName>
            </value>
            <value>
                <fullName>Kalamboli</fullName>
            </value>
            <value>
                <fullName>Kalbadevi</fullName>
            </value>
            <value>
                <fullName>Kalyan</fullName>
                <label>KALYAN</label>
            </value>
            <value>
                <fullName>Kamothe</fullName>
            </value>
            <value>
                <fullName>Kandivali</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/RW_Project__c.field-meta.xml
<CustomField>
    <fullName>RW_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please Select an Active Project</errorMessage>
        <filterItems>
            <field>Project__c.RW_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Location__c.field-meta.xml
<CustomField>
    <fullName>RW_Location__c</fullName>
    <label>Preferred Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airoli</fullName>
            </value>
            <value>
                <fullName>Ambernath</fullName>
            </value>
            <value>
                <fullName>Andheri</fullName>
            </value>
            <value>
                <fullName>Antop Hill</fullName>
            </value>
            <value>
                <fullName>Badlapur</fullName>
                <label>BADLAPUR</label>
            </value>
            <value>
                <fullName>Bandra</fullName>
            </value>
            <value>
                <fullName>Bhandup</fullName>
            </value>
            <value>
                <fullName>Borivali</fullName>
            </value>
            <value>
                <fullName>Byculla</fullName>
            </value>
            <value>
                <fullName>CBD Belapur</fullName>
            </value>
            <value>
                <fullName>Chembur</fullName>
            </value>
            <value>
                <fullName>Churchagte</fullName>
            </value>
            <value>
                <fullName>Colaba</fullName>
            </value>
            <value>
                <fullName>Cuffe Parade</fullName>
            </value>
            <value>
                <fullName>Dadar</fullName>
            </value>
            <value>
                <fullName>Dahisar</fullName>
            </value>
            <value>
                <fullName>Dombivali</fullName>
                <label>Dombivli</label>
            </value>
            <value>
                <fullName>Fort</fullName>
            </value>
            <value>
                <fullName>Ghansoli</fullName>
            </value>
            <value>
                <fullName>Ghatkopar</fullName>
            </value>
            <value>
                <fullName>Goregaon</fullName>
            </value>
            <value>
                <fullName>Govandi</fullName>
            </value>
            <value>
                <fullName>Jogeshwari</fullName>
            </value>
            <value>
                <fullName>Juhu</fullName>
            </value>
            <value>
                <fullName>Juinagar</fullName>
            </value>
            <value>
                <fullName>Kalamboli</fullName>
            </value>
            <value>
                <fullName>Kalbadevi</fullName>
            </value>
            <value>
                <fullName>Kalyan</fullName>
                <label>KALYAN</label>
            </value>
            <value>
                <fullName>Kamothe</fullName>
            </value>
            <value>
                <fullName>Kandivali</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>RW_Mobile_No__c</fullName>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RW_Project__c.field-meta.xml
<CustomField>
    <fullName>RW_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/WhatsApp_Bot_Project_Image_File_Id__c.field-meta.xml
<CustomField>
    <fullName>WhatsApp_Bot_Project_Image_File_Id__c</fullName>
    <label>WhatsApp Bot Project Image File Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LockatedApp_LoyaltyLeads.cls
@RestResource(urlMapping='/loyalty/*')
global without sharing class LockatedApp_LoyaltyLeads {
    
    @HttpGet
    global static void doGet(){
        
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        Map<String, Object> errorResult = new Map<String, Object>();
        String bkgId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        if(String.isBlank(bkgId) || bkgId == 'referrals'){
            errorResult.put('status', 'error');
            errorResult.put('message', 'Please pass valid Booking Id');
            res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
            res.statusCode = 400;
        }else{
            try{
                List<Booking__c> bkg = [SELECT Id, Opportunity__r.Account.Mobile_No__c FROM Booking__c WHERE Id =: bkgId];
                if(bkg.size() > 0){
                    LoyaltyLeads det = new LoyaltyLeads();
                    List<Lead> loyaltyLeads = [SELECT Id, RW_Mobile_No__c,RW_Project__r.Name,RW_Location__c,CreatedDate,RW_Project__r.WhatsApp_Bot_Project_Image_File_Id__c FROM Lead WHERE RW_Mobile_No__c =: bkg[0].Opportunity__r.Account.Mobile_No__c];
                    List<String> projImageIds = new List<String>();
                    for(Lead ld : loyaltyLeads){
                        projImageIds.add(ld.RW_Project__r.WhatsApp_Bot_Project_Image_File_Id__c); 
                    }
                    Map<String, String> projImageLink = new Map<String, String>();
                    if(projImageIds.size() > 0){
                        List<ContentDistribution> distrList = [SELECT Id, Name, DistributionPublicUrl, ContentDocumentId FROM ContentDistribution 
                                                               WHERE ContentDocumentId =: projImageIds];
                        for(ContentDistribution dist : distrList){
                            projImageLink.put(dist.ContentDocumentId, dist.DistributionPublicUrl);
                        }
                    }
                    List<Loyalty> loyaltyList = new List<Loyalty>();
                    for(Lead ld : loyaltyLeads){
                        Loyalty loy = new Loyalty();
                        loy.projectName = ld.RW_Project__r.Name;
                        loy.location = ld.RW_Location__c;
                        loy.enquiredOn = String.valueOf(ld.CreatedDate);
                        loy.imageUrl = projImageLink.get(ld.RW_Project__r.WhatsApp_Bot_Project_Image_File_Id__c);
                        loyaltyList.add(loy);
                    }
                    det.myEnquiries = loyaltyList;
                    //return null;
                    res.responseBody = Blob.valueOf(JSON.serialize(det));
                    res.statusCode = 200;
                }else{
                    errorResult.put('status', 'error');
                    errorResult.put('message', 'Booking record not found');
                    res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                    res.statusCode = 400;
                }
                
            }catch(exception e){
                errorResult.put('status', 'error');
                errorResult.put('message', e.getMessage() + ';  ' + e.getStackTraceString());
                res.responseBody = Blob.valueOf(JSON.serialize(errorResult));
                res.statusCode = 400;
            }
            
        }    
        
    }
    
    global class LoyaltyLeads{
        public List<Loyalty> myEnquiries;
    }
    
    public class Loyalty{
        public string projectName;
        public string location;
        public string enquiredOn;
        public string imageUrl;
    }
}